apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ingress-nginx
      # version: "4.11.2"   # (optional) pin a version; omit to take latest
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      kind: DaemonSet
      hostPort:
        enabled: true
      ingressClassResource:
        name: nginx
        enabled: true
        default: false
      ingressClassByName: true
      service:
        type: ClusterIP      # hostPort exposes 80/443 on the VM, no LB/NodePort needed
