apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/infrastructure/jenkins
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
